// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcWAcIjhCnYZrR7eoKi1LdrWsl7E7R8Lg',
    appId: '1:296301407702:web:e2137eb1a8234bcdd44877',
    messagingSenderId: '296301407702',
    projectId: 'sufyan-portfolio-79a11',
    authDomain: 'sufyan-portfolio-79a11.firebaseapp.com',
    storageBucket: 'sufyan-portfolio-79a11.firebasestorage.app',
    measurementId: 'G-TP39D7VLEG',
    databaseURL: 'https://sufyan-portfolio-79a11-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxDn_tZqb_r8NEVXqjQCrLlUQqfyn2EWM',
    appId: '1:296301407702:android:f8d9a85ed1f6dce8d44877',
    messagingSenderId: '296301407702',
    projectId: 'sufyan-portfolio-79a11',
    storageBucket: 'sufyan-portfolio-79a11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoE7PApKmORNIjCW7qWMFdj_hMFQEobJ4',
    appId: '1:296301407702:ios:0c114ff4cfc3e791d44877',
    messagingSenderId: '296301407702',
    projectId: 'sufyan-portfolio-79a11',
    storageBucket: 'sufyan-portfolio-79a11.firebasestorage.app',
    iosBundleId: 'com.example.sufyanPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoE7PApKmORNIjCW7qWMFdj_hMFQEobJ4',
    appId: '1:296301407702:ios:0c114ff4cfc3e791d44877',
    messagingSenderId: '296301407702',
    projectId: 'sufyan-portfolio-79a11',
    storageBucket: 'sufyan-portfolio-79a11.firebasestorage.app',
    iosBundleId: 'com.example.sufyanPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcWAcIjhCnYZrR7eoKi1LdrWsl7E7R8Lg',
    appId: '1:296301407702:web:2eab692732ab36c1d44877',
    messagingSenderId: '296301407702',
    projectId: 'sufyan-portfolio-79a11',
    authDomain: 'sufyan-portfolio-79a11.firebaseapp.com',
    storageBucket: 'sufyan-portfolio-79a11.firebasestorage.app',
    measurementId: 'G-4WY0FVZ15G',
  );
}
